---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-test
  namespace: default
spec:
  secretName: example-test-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "nginx.example.com"
  dnsNames:
    - "nginx.example.com"
